import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  shell: { flex: 1, backgroundColor: "#f4f2ec" },
  loginShell: { flex: 1, backgroundColor: "#102522" },
  loginContent: { flexGrow: 1, justifyContent: "center", padding: 18, gap: 12 },
  loginContentCompact: { paddingVertical: 10, gap: 8 },
  loginHeader: { gap: 4 },
  loginEyebrow: { color: "#c7a85a", fontSize: 12, fontWeight: "700" },
  loginProduct: { color: "white", fontSize: 34, fontWeight: "700" },
  loginSubtitle: { color: "#cfe8df", fontSize: 14, lineHeight: 19 },
  loginPanel: {
    padding: 14,
    backgroundColor: "#fffaf0",
    borderRadius: 8,
    gap: 7,
    shadowColor: "#000",
    shadowOpacity: 0.22,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8
  },
  formTitle: { color: "#102522", fontSize: 21, fontWeight: "700" },
  formSubTitle: { color: "#66716d", marginTop: 2, fontSize: 13, lineHeight: 18 },
  formMessage: { padding: 8, borderRadius: 6, backgroundColor: "#eef6f2", color: "#146c5c" },
  header: { paddingHorizontal: 20, paddingVertical: 14, backgroundColor: "#102522", flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  product: { fontSize: 22, fontWeight: "700", color: "white" },
  subtitle: { color: "#cfe8df", marginTop: 2 },
  badge: { color: "#102522", backgroundColor: "#d7efe6", paddingHorizontal: 10, paddingVertical: 5, borderRadius: 6, overflow: "hidden" },
  userPill: { flexDirection: "row", alignItems: "center", gap: 8, padding: 4, paddingRight: 9, borderRadius: 999, backgroundColor: "#183531" },
  avatar: { width: 30, height: 30, borderRadius: 15, backgroundColor: "#d7efe6", alignItems: "center", justifyContent: "center" },
  avatarText: { color: "#102522", fontWeight: "700" },
  userName: { color: "white", fontWeight: "700", maxWidth: 86 },
  userMenu: {
    position: "absolute",
    top: 62,
    right: 12,
    zIndex: 10,
    width: 260,
    padding: 12,
    borderRadius: 8,
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: "#e3dece",
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
    gap: 8
  },
  userMenuName: { color: "#102522", fontSize: 16, fontWeight: "700" },
  userMenuPhone: { color: "#6b7471", fontSize: 12 },
  menuDivider: { height: 1, backgroundColor: "#ebe4d4", marginVertical: 2 },
  menuLabel: { color: "#394341", fontWeight: "700", fontSize: 13 },
  menuOrgItem: { padding: 10, borderRadius: 8, borderWidth: 1, borderColor: "#ede7d8", flexDirection: "row", justifyContent: "space-between", gap: 8 },
  menuOrgItemActive: { borderColor: "#146c5c", backgroundColor: "#eef6f2" },
  menuOrgName: { color: "#102522", fontWeight: "700" },
  menuLogout: { minHeight: 36, alignItems: "center", justifyContent: "center" },
  content: { padding: 16, gap: 12, paddingBottom: 92 },
  title: { fontSize: 24, fontWeight: "700", color: "#102522" },
  noticeBanner: { padding: 10, borderRadius: 6, backgroundColor: "#e0f1ea", color: "#146c5c", fontWeight: "700" },
  panel: { padding: 14, backgroundColor: "white", borderRadius: 8, gap: 10 },
  label: { color: "#394341", fontWeight: "700", marginTop: 0, fontSize: 13 },
  sectionTitle: { color: "#102522", fontSize: 17, fontWeight: "700" },
  input: { minHeight: 40, borderWidth: 1, borderColor: "#d9d3c4", borderRadius: 6, paddingHorizontal: 10, color: "#102522", backgroundColor: "white" },
  dateFieldWrap: { position: "relative", flexGrow: 1, flexBasis: 104 },
  dateField: { justifyContent: "center" },
  dateFieldText: { color: "#102522" },
  dateFieldPlaceholder: { color: "#9a9488" },
  datePickerPanel: {
    position: "absolute",
    top: 44,
    left: 0,
    zIndex: 30,
    width: 260,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#d9d3c4",
    backgroundColor: "white",
    shadowColor: "#000",
    shadowOpacity: 0.16,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10
  },
  datePickerHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 8 },
  datePickerTitle: { color: "#102522", fontWeight: "700" },
  datePickerNav: { width: 32, height: 32, borderRadius: 6, alignItems: "center", justifyContent: "center", backgroundColor: "#eef6f2" },
  datePickerNavText: { color: "#146c5c", fontSize: 22, lineHeight: 24, fontWeight: "700" },
  datePickerGrid: { flexDirection: "row", flexWrap: "wrap" },
  datePickerWeekday: { width: "14.2857%", paddingVertical: 5, textAlign: "center", color: "#6b7471", fontSize: 12, fontWeight: "700" },
  datePickerDay: { width: "14.2857%", height: 32, alignItems: "center", justifyContent: "center", borderRadius: 6 },
  datePickerDayActive: { backgroundColor: "#146c5c" },
  datePickerDayText: { color: "#102522", fontWeight: "700" },
  datePickerDayTextActive: { color: "white" },
  datePickerModalOverlay: { flex: 1, padding: 18, backgroundColor: "rgba(16, 37, 34, 0.28)", alignItems: "center", justifyContent: "center" },
  datePickerModalPanel: {
    width: 320,
    maxWidth: "100%",
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#d9d3c4",
    backgroundColor: "white",
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 16
  },
  codeRow: { flexDirection: "row", gap: 8 },
  codeInput: { flex: 1 },
  codeButton: { width: 104, minHeight: 40, borderRadius: 6, borderWidth: 1, borderColor: "#146c5c", alignItems: "center", justifyContent: "center" },
  textarea: { minHeight: 88, paddingTop: 10, textAlignVertical: "top" },
  button: { minHeight: 40, borderRadius: 6, backgroundColor: "#146c5c", alignItems: "center", justifyContent: "center" },
  buttonDisabled: { opacity: 0.48 },
  buttonText: { color: "white", fontWeight: "700" },
  secondaryButton: { minHeight: 40, borderRadius: 6, borderWidth: 1, borderColor: "#146c5c", alignItems: "center", justifyContent: "center" },
  secondaryButtonText: { color: "#146c5c", fontWeight: "700" },
  switchAuthButton: { minHeight: 28, alignItems: "center", justifyContent: "center" },
  switchAuthText: { color: "#146c5c", fontWeight: "700" },
  segment: { flexDirection: "row", padding: 3, borderRadius: 6, backgroundColor: "#ece5d5" },
  segmentItem: { flex: 1, minHeight: 34, borderRadius: 5, alignItems: "center", justifyContent: "center" },
  segmentItemActive: { backgroundColor: "white" },
  segmentText: { color: "#596460", fontWeight: "700" },
  segmentTextActive: { color: "#102522" },
  metricRow: { flexDirection: "row", gap: 10 },
  metric: { flex: 1, backgroundColor: "white", borderRadius: 8, padding: 12 },
  metricValue: { marginTop: 4, fontSize: 24, color: "#102522", fontWeight: "700" },
  notice: { padding: 14, backgroundColor: "white", borderRadius: 8, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  noticeText: { color: "#102522", fontSize: 15 },
  link: { color: "#146c5c", fontWeight: "700" },
  card: { padding: 14, backgroundColor: "white", borderRadius: 8, flexDirection: "row", justifyContent: "space-between", gap: 12 },
  cardTitle: { color: "#102522", fontSize: 17, fontWeight: "700" },
  cardStat: { color: "#146c5c", fontWeight: "700" },
  apartmentListCard: { padding: 12, borderWidth: 1, borderColor: "#e3dece", borderRadius: 8, gap: 10, backgroundColor: "#fffdf7" },
  muted: { color: "#6b7471" },
  orgOption: { padding: 12, borderWidth: 1, borderColor: "#e3dece", borderRadius: 8, flexDirection: "row", justifyContent: "space-between", gap: 12 },
  orgOptionActive: { borderColor: "#146c5c", backgroundColor: "#eef6f2" },
  memberCard: { padding: 12, borderWidth: 1, borderColor: "#e3dece", borderRadius: 8, gap: 10, backgroundColor: "#fffdf7" },
  memberHeader: { flexDirection: "row", justifyContent: "space-between", gap: 12 },
  roleBadge: { color: "#146c5c", fontWeight: "700" },
  roleActions: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  smallButton: { minHeight: 34, paddingHorizontal: 10, borderRadius: 6, borderWidth: 1, borderColor: "#d9d3c4", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  smallButtonActive: { backgroundColor: "#146c5c", borderColor: "#146c5c" },
  smallButtonText: { color: "#394341", fontWeight: "700" },
  smallButtonTextActive: { color: "white" },
  smallDangerButton: { minHeight: 34, paddingHorizontal: 10, borderRadius: 6, borderWidth: 1, borderColor: "#c8674e", alignItems: "center", justifyContent: "center" },
  smallDangerText: { color: "#b14f38", fontWeight: "700" },
  tabbar: { position: "absolute", left: 0, right: 0, bottom: 0, minHeight: 64, padding: 8, backgroundColor: "white", borderTopWidth: 1, borderTopColor: "#e4dece", flexDirection: "row", gap: 6 },
  tab: { flex: 1, borderRadius: 6, alignItems: "center", justifyContent: "center" },
  tabActive: { backgroundColor: "#146c5c" },
  tabText: { color: "#4f5b58", fontSize: 13 },
  tabTextActive: { color: "white", fontWeight: "700" },

  // 新增：首页
  statRow: { flexDirection: "row", gap: 10 },
  statBlock: { flex: 1, backgroundColor: "white", borderRadius: 8, padding: 14, gap: 6 },
  statValue: { fontSize: 20, color: "#102522", fontWeight: "700" },
  statLabel: { color: "#6b7471", fontSize: 12 },
  todoItem: { padding: 14, backgroundColor: "white", borderRadius: 8, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  todoContent: { flex: 1, gap: 4 },
  todoBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 999, backgroundColor: "#e0f1ea", color: "#146c5c", fontSize: 12, fontWeight: "700", overflow: "hidden" },
  todoBadgeDanger: { backgroundColor: "#fceeee", color: "#b14f38" },
  todoBadgeWarning: { backgroundColor: "#fff3e0", color: "#c77700" },
  homeHero: { padding: 16, borderRadius: 8, backgroundColor: "#102522", gap: 14 },
  homeEyebrow: { color: "#c7a85a", fontSize: 12, fontWeight: "700" },
  homeHeroValue: { marginTop: 4, color: "white", fontSize: 30, fontWeight: "700" },
  homeHeroGrid: { flexDirection: "row", justifyContent: "space-between", gap: 10, paddingTop: 12, borderTopWidth: 1, borderTopColor: "#294743" },
  homeHeroLabel: { color: "#cfe8df", fontSize: 12 },
  homeHeroMetric: { marginTop: 3, color: "white", fontSize: 15, fontWeight: "700" },
  refreshButton: { minHeight: 34, paddingHorizontal: 12, borderRadius: 6, alignItems: "center", justifyContent: "center", backgroundColor: "#d7efe6" },
  refreshButtonText: { color: "#102522", fontWeight: "700" },
  homeApartmentRow: { paddingVertical: 10, borderTopWidth: 1, borderTopColor: "#eee8da", flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  homeApartmentMain: { flex: 1, gap: 3 },
  homeApartmentStat: { alignItems: "flex-end", gap: 3 },

  // 新增：房间
  roomCard: { padding: 14, backgroundColor: "white", borderRadius: 8, gap: 10 },
  roomGrid: { gap: 10 },
  roomCardActive: { borderWidth: 1, borderColor: "#146c5c", backgroundColor: "#eef6f2" },
  roomHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 12 },
  roomHeaderBadges: { alignItems: "flex-end", gap: 5, flexShrink: 0 },
  roomActions: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 999, fontSize: 12, fontWeight: "700", overflow: "hidden" },
  statusVacant: { backgroundColor: "#e0f1ea", color: "#146c5c" },
  statusOccupied: { backgroundColor: "#fff3e0", color: "#c77700" },
  statusMaintenance: { backgroundColor: "#fceeee", color: "#b14f38" },
  statusReserved: { backgroundColor: "#ece5d5", color: "#7a6a4f" },

  // 新增：筛选与空状态
  filterBar: { flexDirection: "row", gap: 8 },
  filterButton: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 6, borderWidth: 1, borderColor: "#d9d3c4", backgroundColor: "white" },
  filterButtonActive: { borderColor: "#146c5c", backgroundColor: "#eef6f2" },
  filterButtonText: { color: "#394341", fontWeight: "700", fontSize: 13 },
  filterButtonTextActive: { color: "#146c5c" },
  emptyText: { color: "#9a9488", textAlign: "center", marginTop: 24 },

  // 新增：详情面板
  detailPanel: { padding: 14, backgroundColor: "#fffdf7", borderRadius: 8, borderWidth: 1, borderColor: "#e3dece", gap: 8 },
  detailRow: { flexDirection: "row", justifyContent: "space-between", gap: 12 },
  sectionHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10, flexWrap: "wrap" },
  formGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  formField: { flexGrow: 1, flexBasis: 104, gap: 4 },
  fieldLabel: { color: "#6b7471", fontSize: 12, fontWeight: "700" },
  gridInput: { flexGrow: 1, flexBasis: 104 },
  actionButton: { flex: 1 },
  batchRoomPanel: { padding: 10, borderRadius: 8, borderWidth: 1, borderColor: "#e3dece", backgroundColor: "#fffdf7", gap: 8 },
  batchRoomGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  batchRoomButton: { minWidth: 62, minHeight: 34, paddingHorizontal: 10, borderRadius: 6, borderWidth: 1, borderColor: "#d9d3c4", alignItems: "center", justifyContent: "center", backgroundColor: "white" },
  batchRoomButtonActive: { borderColor: "#146c5c", backgroundColor: "#146c5c" },
  batchRoomButtonText: { color: "#394341", fontWeight: "700" },
  batchRoomButtonTextActive: { color: "white" },
  feeItem: { padding: 10, borderRadius: 8, borderWidth: 1, borderColor: "#e3dece", backgroundColor: "#fffdf7", flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  feeItemActive: { borderColor: "#146c5c", backgroundColor: "#eef6f2" },
  modalOverlay: { flex: 1, padding: 16, backgroundColor: "rgba(16, 37, 34, 0.42)", justifyContent: "center" },
  modalCard: { maxHeight: "88%", padding: 14, borderRadius: 8, backgroundColor: "white", gap: 10 },
  modalScrollContent: { gap: 10 },

  // 新增：设置与子页面
  settingItem: { padding: 14, backgroundColor: "white", borderRadius: 8, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  settingItemText: { color: "#102522", fontSize: 15, fontWeight: "700" },
  subPageHeader: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 4 },
  backButton: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 6, backgroundColor: "#eef6f2" },
  backButtonText: { color: "#146c5c", fontWeight: "700" },
  planCard: { padding: 12, borderWidth: 1, borderColor: "#e3dece", borderRadius: 8, gap: 10, backgroundColor: "#fffdf7" },
  planCardActive: { borderColor: "#146c5c", backgroundColor: "#eef6f2" },
  planHeader: { flexDirection: "row", justifyContent: "space-between", gap: 12 },
  planPrice: { marginTop: 4, color: "#146c5c", fontSize: 18, fontWeight: "700" },
  quotaRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  quotaText: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, backgroundColor: "#f4f2ec", color: "#394341", fontSize: 12, overflow: "hidden" },

  // 新增：账单
  billCard: { padding: 14, backgroundColor: "white", borderRadius: 8, gap: 10, borderWidth: 1, borderColor: "#e3dece" },
  billAmountRow: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", gap: 12 },
  billSummaryAside: { alignItems: "flex-end", gap: 2 },
  billCardFooter: { paddingTop: 8, borderTopWidth: 1, borderTopColor: "#eee8da", flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  billAmount: { color: "#102522", fontSize: 20, fontWeight: "700" },
  billLine: { paddingVertical: 8, borderTopWidth: 1, borderTopColor: "#eee8da", flexDirection: "row", justifyContent: "space-between", gap: 10 },
  billDetailBlock: { borderTopWidth: 1, borderTopColor: "#eee8da", paddingTop: 8, gap: 6 },
  billItemLine: { flexDirection: "row", justifyContent: "space-between", gap: 10, paddingLeft: 8 },
  billChoiceList: { gap: 8 },
  readingRow: { padding: 12, backgroundColor: "white", borderRadius: 8, borderWidth: 1, borderColor: "#e3dece", flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 }
  ,

  // 新增：任务表单层
  taskSheetOverlay: { flex: 1, backgroundColor: "rgba(16, 37, 34, 0.42)" },
  taskSheetOverlay_bottom: { justifyContent: "flex-end" },
  taskSheetOverlay_drawer: { justifyContent: "flex-end" },
  taskSheetOverlay_dialog: { justifyContent: "center", padding: 18 },
  taskSheetCard: { backgroundColor: "white", gap: 10, padding: 14 },
  taskSheetCard_bottom: { maxHeight: "78%", borderTopLeftRadius: 12, borderTopRightRadius: 12 },
  taskSheetCard_drawer: { maxHeight: "90%", minHeight: "62%", borderTopLeftRadius: 12, borderTopRightRadius: 12 },
  taskSheetCard_dialog: { maxHeight: "78%", borderRadius: 8 },
  taskSheetTitleBlock: { flex: 1, gap: 2 },
  taskSheetContent: { gap: 10, paddingBottom: 2 },
  taskSheetFooter: { gap: 8, paddingTop: 8, borderTopWidth: 1, borderTopColor: "#eee8da" }
});
